name: Build My Application

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:   
    name: Build App
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
      - uses: actions/checkout@v2 
      - name: Print Current Directory
        run: pwd
      - name: List dir
        run: ls
